; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = seeed_xiao_esp32c6
src_dir = ap_scan_wifi
lib_dir = ../libraries

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3
monitor_speed = 460800
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8

[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6
monitor_speed = 460800
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_58:E6:C5:14:71:88-if00
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
monitor_speed = 460800
lib_deps = 
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8
